# Generated by Django 5.2 on 2025-05-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='faq',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
