# Generated by Django 5.2 on 2025-05-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_faq_message_type_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='default_password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
